[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npx ts-node --project tsconfig.json index.ts"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
